### PR TITLE
Fix failing managers test cases

### LINKED ISSUE #81: Fix failing managers test cases
- LogicManagerTest, ModelManagerTest, AddressBookTest

### PR DESCRIPTION
**Pull request by snowstopxt**
Fix failing managers test cases

## Description

Fix #81

Fixed managers test cases

## Changes made

LogicManagerTest (2 left), ModelManagerTest, AddressBookTest (1 left)

## Testing Steps

1. Run ./gradlew test

### CODE REVIEW

File: src/test/java/seedu/address/model/AddressBookTest.java [hunk 1]
```diff
@@ -75,10 +75,10 @@ public void hasItem_itemInAddressBook_returnsTrue() {
     }
 
     @Test
-    public void hasItem_itemWithSameIdentityFieldsInAddressBook_returnsTrue() {
+    public void hasItem_itemWithSameIdentityFieldsInAddressBook_returnsFalse() {
         addressBook.addItem(APPLE);
         InternshipApplication editedApple = new InternshipApplicationBuilder(APPLE).withRole(VALID_ROLE_BOFA).build();
-        assertTrue(addressBook.hasItem(editedApple));
+        assertFalse(addressBook.hasItem(editedApple));
```
Comment (ZweZeya) [inline src/test/java/seedu/address/model/AddressBookTest.java:81]: Good change since our app has a different behaviour

**Review by ZweZeya — APPROVED** [review]
